#!/usr/bin/env python3
"""Install graphify's own SKILL.md, rewritten for this machine's GRAPHIFY_OUT.

graphify's CLI reads the output directory from `GRAPHIFY_OUT` (graphify/paths.py),
but the shipped skill hardcodes the literal `graphify-out` in 88 places and never
mentions the variable. So with `GRAPHIFY_OUT=.graphify` set, the two halves of the
same tool disagree: the skill runs `mkdir -p graphify-out` and looks for
`graphify-out/graph.json` while the CLI writes to `.graphify/`. Its fast path
("graph already exists → just query it") keys on that same missing file, so every
invocation would fall through to a full rebuild.

Rewriting on install keeps one source of truth — the installed package — without
vendoring 41 KB into this repo where it would go stale on the next upgrade.

Safety of the blanket replace, audited against graphify 0.9.38: all 88
occurrences are path-initial (84 followed by `/`, the rest by a newline or space;
preceded only by space, backtick, quote, or `/`), and none sits inside a longer
identifier. A word-boundary check found zero violations, so a plain string
replace cannot corrupt prose or a different token.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

DEFAULT_OUT = "graphify-out"

# Marker so the file is recognisable as generated. Placed after the YAML
# frontmatter, which must stay at line 1 for the skill loader.
BANNER = (
    "<!-- Generated by claudebase installer/scripts/render_graphify_skill.py\n"
    "     from graphify {version} skill.md, with {old} rewritten to {new}\n"
    "     (GRAPHIFY_OUT in config/settings.json).\n"
    "     Do not edit here — the next install.sh overwrites this file.\n"
    "     Upgrading graphify does NOT refresh it on its own: re-run install.sh,\n"
    "     which re-renders whenever the package's skill.md differs. The version\n"
    "     above is the one this copy was built from — compare it with\n"
    "     `graphify --version` if the skill and the CLI seem to disagree. -->\n"
)


def rewrite(text: str, out_dir: str, version: str = "unknown") -> str:
    """Return `text` with the hardcoded output dir replaced by `out_dir`."""
    if out_dir == DEFAULT_OUT:
        return text
    body = text.replace(DEFAULT_OUT, out_dir)
    banner = BANNER.format(old=DEFAULT_OUT, new=out_dir, version=version)
    return insert_after_frontmatter(body, banner)


def insert_after_frontmatter(text: str, banner: str) -> str:
    """Put `banner` right after a leading `---` YAML block, else at the top.

    The skill loader reads frontmatter from line 1, so the banner must never
    precede it.
    """
    if not text.startswith("---"):
        return banner + text
    end = text.find("\n---", 3)
    if end == -1:
        return banner + text
    close = text.find("\n", end + 1)
    if close == -1:
        return banner + text
    return text[: close + 1] + "\n" + banner + text[close + 1 :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render graphify's SKILL.md for this machine.")
    parser.add_argument("--src", required=True, help="skill.md inside the installed graphify package")
    parser.add_argument("--dst", required=True, help="target SKILL.md under ~/.claude/skills/graphify/")
    parser.add_argument("--out-dir", required=True, help="value of GRAPHIFY_OUT")
    parser.add_argument("--source-version", default="unknown", help="graphify version the source came from")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    src, dst = Path(args.src), Path(args.dst)
    if not src.is_file():
        return 0

    rendered = rewrite(src.read_text(encoding="utf-8"), args.out_dir, args.source_version)

    # Idempotent: identical content means no write and no log line, so a re-run
    # of install.sh stays silent.
    if dst.is_file() and dst.read_text(encoding="utf-8") == rendered:
        return 0
    if args.dry_run:
        print(f"[dry-run] would write {dst} (GRAPHIFY_OUT={args.out_dir})")
        return 0

    # A previous install may have left a symlink into the package; unlink first
    # so the write does not follow it and edit the package in place.
    if dst.is_symlink() or dst.exists():
        dst.unlink()
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(rendered, encoding="utf-8")
    print(f"[install]   graphify skill rendered -> {dst} (GRAPHIFY_OUT={args.out_dir})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
