#!/usr/bin/env python3
"""Install graphify's own SKILL.md, rewritten for this machine's GRAPHIFY_OUT.

graphify's CLI reads the output directory from `GRAPHIFY_OUT` (graphify/paths.py),
but the shipped skill hardcodes the literal `graphify-out` in 88 places and never
mentions the variable. So with `GRAPHIFY_OUT=.graphify` set, the two halves of the
same tool disagree: the skill runs `mkdir -p graphify-out` and looks for
`graphify-out/graph.json` while the CLI writes to `.graphify/`. Its fast path
("graph already exists → just query it") keys on that same missing file, so every
invocation would fall through to a full rebuild.

Rewriting on install keeps one source of truth — the installed package — without
vendoring 41 KB into this repo where it would go stale on the next upgrade.

Safety of the blanket replace, audited against graphify 0.9.38: all 88
occurrences are path-initial (84 followed by `/`, the rest by a newline or space;
preceded only by space, backtick, quote, or `/`), and none sits inside a longer
identifier. A word-boundary check found zero violations, so a plain string
replace cannot corrupt prose or a different token.

The skill is a directory, not one file. `skill.md` delegates its heavier flows to
a sibling `references/` (extraction-spec.md is the subagent prompt itself; the
`--update`, `query`, `add`/`--watch`, export, and merge runbooks live there too).
Rendering only skill.md left that directory absent, which fails twice: the Step 3
semantic pass cannot load the extraction prompt at all, and every reference that
did arrive would still say `graphify-out` — 62 occurrences across 6 files against
graphify 0.9.38, concentrated in update.md (20) and query.md (17). That is exactly
the CLI-vs-skill split this script exists to close, so the references get the same
rewrite and travel with skill.md.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

DEFAULT_OUT = "graphify-out"

# Marker so the file is recognisable as generated. Placed after the YAML
# frontmatter, which must stay at line 1 for the skill loader.
BANNER = (
    "<!-- Generated by claudebase installer/scripts/render_graphify_skill.py\n"
    "     from graphify {version} skill.md, with {old} rewritten to {new}\n"
    "     (GRAPHIFY_OUT in config/settings.json).\n"
    "     Do not edit here — the next install.sh overwrites this file.\n"
    "     Upgrading graphify does NOT refresh it on its own: re-run install.sh,\n"
    "     which re-renders whenever the package's skill.md differs. The version\n"
    "     above is the one this copy was built from — compare it with\n"
    "     `graphify --version` if the skill and the CLI seem to disagree. -->\n"
)


def rewrite(text: str, out_dir: str, version: str = "unknown") -> str:
    """Return `text` with the hardcoded output dir replaced by `out_dir`.

    A file that never mentions `graphify-out` comes back byte-identical — no
    rewrite, and therefore no banner. That is not a cosmetic nicety: one of
    these files is a CACHE KEY. graphify buckets its semantic-extraction cache
    by `prompt_fingerprint()`, a sha256 over the WHOLE TEXT of
    `references/extraction-spec.md` (graphify/cache.py), so anything this
    script prepends becomes part of the extraction prompt as far as the cache
    is concerned — including the `{version}` in BANNER, which is provenance,
    not instruction.

    Measured on the obsidian vault 2026-08-11: with the banner present,
    changing only `graphify 0.9.39` to `0.9.38` moved the bucket from
    `p7814ca696b13` to `p868ee8799dae`. Every graphify upgrade therefore
    orphaned the whole semantic cache even when the prompt body was
    byte-identical, and the corpus was re-extracted at full LLM cost — ~10M
    tokens for 898 files on that vault, for a version string.

    The banner also made the file MACHINE-specific, which breaks the other
    half of the design: the cache is committed to git precisely so a second
    machine restores it without re-paying. A machine on the default
    `GRAPHIFY_OUT=graphify-out` takes the early return below and gets the
    pristine file, while `.graphify` machines got a banner — two buckets for
    one prompt, so the shared cache never hit across them.

    `extraction-spec.md` carries zero `graphify-out` occurrences against
    graphify 0.9.39 (the paths it names are substituted by the caller), so
    skipping the no-op rewrite leaves it identical to the packaged prompt.
    Its fingerprint then moves when graphify actually changes the prompt,
    which is the behaviour the cache was designed around. `hooks.md` is the
    other zero-occurrence file and simply loses a banner it never needed.
    """
    if out_dir == DEFAULT_OUT:
        return text
    body = text.replace(DEFAULT_OUT, out_dir)
    if body == text:
        return text
    banner = BANNER.format(old=DEFAULT_OUT, new=out_dir, version=version)
    return insert_after_frontmatter(body, banner)


def insert_after_frontmatter(text: str, banner: str) -> str:
    """Put `banner` right after a leading `---` YAML block, else at the top.

    The skill loader reads frontmatter from line 1, so the banner must never
    precede it.
    """
    if not text.startswith("---"):
        return banner + text
    end = text.find("\n---", 3)
    if end == -1:
        return banner + text
    close = text.find("\n", end + 1)
    if close == -1:
        return banner + text
    return text[: close + 1] + "\n" + banner + text[close + 1 :]


def find_references(pkg_dir: Path, platform: str = "claude") -> Path | None:
    """Locate the platform's `references/` inside the installed graphify package.

    It does not sit beside skill.md. graphify 0.9.38 ships ONE top-level
    `skill.md` at the package root and a PER-PLATFORM `skills/<platform>/
    references/` (claude, windows, codex, opencode, …) — so the obvious
    `skill.md.parent / "references"` resolves to a path that does not exist, and
    the copy silently does nothing. Checked in that order, with the flat layout
    kept as a fallback in case a later release moves it.
    """
    for candidate in (pkg_dir / "skills" / platform / "references", pkg_dir / "references"):
        if candidate.is_dir():
            return candidate
    return None


def render_references(src_dir: Path, dst_dir: Path, out_dir: str, version: str, dry_run: bool) -> int:
    """Mirror `src_dir` into `dst_dir` with the same GRAPHIFY_OUT rewrite.

    Returns the number of files written. Missing source is not an error — an
    older graphify shipped skill.md alone.
    """
    if not src_dir.is_dir():
        return 0
    written = 0
    for src in sorted(src_dir.glob("*.md")):
        rendered = rewrite(src.read_text(encoding="utf-8"), out_dir, version)
        dst = dst_dir / src.name
        if dst.is_file() and dst.read_text(encoding="utf-8") == rendered:
            continue
        if dry_run:
            print(f"[dry-run] would write {dst} (GRAPHIFY_OUT={out_dir})")
            written += 1
            continue
        if dst.is_symlink() or dst.exists():
            dst.unlink()
        dst.parent.mkdir(parents=True, exist_ok=True)
        dst.write_text(rendered, encoding="utf-8")
        written += 1
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render graphify's SKILL.md for this machine.")
    parser.add_argument("--src", required=True, help="skill.md inside the installed graphify package")
    parser.add_argument("--dst", required=True, help="target SKILL.md under ~/.claude/skills/graphify/")
    parser.add_argument("--out-dir", required=True, help="value of GRAPHIFY_OUT")
    parser.add_argument("--source-version", default="unknown", help="graphify version the source came from")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    src, dst = Path(args.src), Path(args.dst)
    if not src.is_file():
        return 0

    rendered = rewrite(src.read_text(encoding="utf-8"), args.out_dir, args.source_version)

    # The references travel with skill.md, and are rendered even when skill.md
    # itself is unchanged: they are separate files, so a run that skipped them
    # before must still be able to fill them in.
    refs_src = find_references(src.parent)
    refs = (
        render_references(refs_src, dst.parent / "references", args.out_dir, args.source_version, args.dry_run)
        if refs_src
        else 0
    )

    # Idempotent: identical content means no write and no log line, so a re-run
    # of install.sh stays silent.
    if dst.is_file() and dst.read_text(encoding="utf-8") == rendered:
        if refs:
            print(f"[install]   graphify skill references rendered -> {dst.parent / 'references'} ({refs} file(s))")
        return 0
    if args.dry_run:
        print(f"[dry-run] would write {dst} (GRAPHIFY_OUT={args.out_dir})")
        return 0

    # A previous install may have left a symlink into the package; unlink first
    # so the write does not follow it and edit the package in place.
    if dst.is_symlink() or dst.exists():
        dst.unlink()
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(rendered, encoding="utf-8")
    print(f"[install]   graphify skill rendered -> {dst} (GRAPHIFY_OUT={args.out_dir})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
